#pragma once

#define DEBUG_MODE

enum class ObjectType
{
    OBJECT_NONE,
    OBJECT_SCREEN,
    OBJECT_WORLD,
};

enum class AnchorType
{
    ANCHOR_NONE,
    ANCHOR_TOP_LEFT,
    ANCHOR_TOP_CENTER,
    ANCHOR_TOP_RIGHT,
    ANCHOR_CENTER_LEFT,
    ANCHOR_CENTER,
    ANCHOR_CENTER_RIGHT,
    ANCHOR_BOTTOM_LEFT,
    ANCHOR_BOTTOM_CENTER,
    ANCHOR_BOTTOM_RIGHT
};